- README.md
Added many more links. Fell free to pick any you want
> Added several links

- README.md
Here a plugin from me, a little JavaFx app and a new section 'Videos' for great JavaFX videos :)
> Add plugin, app and new section 'Videos'.

- README.md
I added an article you might find interesting
> Added TestFX article

- README.md
**Changes:**
- Added Projects, and a web framework
Thanks for creating this potentially, awesome list. If I find anything else, I'll be sure to submit additional pull requests.
> ReadMe: added more projects to list

- README.md
Added links to a couple of my JavaFX projects.
> Added links for FXGraphics2D and Orson Charts

- README.md
APX is a new javafx framework.library that helps to speed up development by creating mvc layouts for a developer thereby structuring the project. It also comes with some libraries that aid in sql connection and Http Connection. it is currently in v0.0.2 which is stable and has room for more development/improvement.
a demo project is avalable at https://github.com/othreecodes/apxdemo
> Added apx - A JavaFX Library for Creating MVC Apps

- README.md
> Adding FXApps

- README.md
Trying to pull this list on global Awesome List ( https://github.com/sindresorhus/awesome/pull/921 )
> [Update] Awesome project logo link

- README.md
I added my article 'Building a JavaFX Search Bar'
> Added Search Bar article

- README.md
Adds GestureFX to the list. The library is production ready.
> Introduce GestureFX library

- README.md
> Add FXForm2 library

- README.md
https://github.com/Oshan96/CustomStage
This is a great tool to reduce the time for the people who need to use a fully customized undecorated javafx stage.
> Add CustomStage

- README.md
Hi , AnimateFX is a JavaFX library I've developed and just released containing +70 ready to use animations .
Thanks 😄
> add AnimateFX

- README.md
Added FX-BorderlessScene on JavaFX Libraries as requested :) #44
> Added FX-BorderlessScene on JavaFX Libraries

- README.md
https://github.com/dlemmermann/PreferencesFX and https://github.com/dlemmermann/PreferencesFX
They are useful libraries / frameworks to use in JavaFX applications, saving time 😃
> Add PreferencesFX and WorkbenchFX

- README.md
JFXAnimation is more or less a fluent builder which lets you build animations the CSS like way.
Thank you for this Awesome list :wink: 
Greetings
> Add JFXAnimation

- README.md
Please consider the addition of [binjr](https://github.com/binjr/binjr) as an entry in Real World Examples.  
[binjr](https://github.com/binjr/binjr) is a time series data browser; it renders time series data produced by other applications as dynamically editable charts and provides many features to navigate through the data in a natural and fluent fashion (drag & drop, zoom, history, detacheable tabs, advanced time-range picker).
> Please consider the addition of https://github.com/binjr/binjr as an entry in Real World Examples

- README.md
> add update4j, fxlauncher and getdown

- README.md
Adding the [Open Lowcode framework](https://github.com/openlowcode/Open-Lowcode). It includes a JavaFX thin client.
> Adding Open Lowcode

- README.md
[Bounding Box Editor](https://github.com/mfl28/BoundingBoxEditor)
Bounding Box Editor is multi-platform JavaFX image annotation application to create and edit ground-truth labels for object detection and segmentation machine learning models.
> Add Bounding Box Editor to real world examples

- README.md
JavaFx WebView debugging with Chrome Dev tools.
> Added Webview debugger

- README.md
Fixing the "developper" typo, putting dots to standardize, as some was with and some without ending dots.  And adding twitter of https://github.com/brunoborges
> Fixing typo, dots and adding twitter

- README.md
[FroXty](https://github.com/iAmGio/froxty) is a new small library which replicates the iOS translucent effect.
> Add FroXty to 'Libraries, Tools and Projects'

- README.md
This adds a UI for controlling a model railway control system.
> Add PI-Rail

- README.md
Adding graph editor (https://github.com/eckig/graph-editor) to the list.
> Add graph-editor

- README.md
My project ([FXTaskbarProgressBar](https://github.com/Dansoftowner/FXTaskbarProgressBar)) has started to gain some popularity. It's an implementation for showing progress on the Windows taskbar easily.
This project supports java 8 and java 11 both.
> Adding FXTaskbarProgressBar project

- README.md
[PrettyZoo](https://github.com/vran-dev/PrettyZoo) is a GUI for [Zookeeper](https://zookeeper.apache.org/) created by JavaFX and Apache Curator Framework.
> Adding PrettyZoo to Real World Examples

- README.md
https://github.com/wiverson/maven-jpackage-template
GitHub template showing how to use JavaFX, Maven, and GitHub Actions to produce native desktop installers for macOS, Windows, Linux.
> https://github.com/wiverson/maven-jpackage-template

- README.md
[Animated](https://github.com/iAmGio/animated) introduces Flutter-inspired implicit animations into JavaFX.
I have also fixed the position of assertj-javafx in the list.
> Added Animated

- README.md
A tool to help you inspect the location and properties of certain components in a window hierarchy.
JavaFX micro-framework to develop JavaFX components very fast with minimal code following MVVM architecture pattern with passive view.
ResumeFX renders a JavaFX view of .json file that follows [jsonresume.org](https://jsonresume.org) standard and has the necessary configuration to be embedded in the web browser thanks to [JPro](https://www.jpro.one).
> Added Component-Inspector, ReactiveDeskFX and ResumeFX

- README.md
[Boomega](https://github.com/Dansoftowner/Boomega) is a modern book explorer & catalog application built with JavaFX.
> Add Boomega to real world examples

- README.md
Resize me is an image resize and compression tool which can easily resize your image based on width, height or percentage.
> Add Resize Me

- README.md
[Actlist](https://github.com/actlist/actlist) is a utility platform to execute your own action list easily and simply.
> Add Actlist

- README.md
A graphical interface for the official *W3C EPUBCheck* conformance checker. It can validate EPUB files and folders and display metadata in an easy-to-use and modern interface. Validation results are displayed as a table or list, and a summary provides a quick overview of the number of errors and warnings that occurred.
> Add EPUBCheckFX to Real World Examples

- README.md
Add the Quarkus "quarkus-fx" extension
> Add quarkus-fx

- README.md
> Add Rich Text Area Project

- README.md
JediTermFX is a Terminal Emulator for JavaFX
> Add JediTermFX
